Grupo02-201610/config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about' => 'pages#about', as: :about

  get '/empresas' => 'empresa#index'
  post 'empresas' => 'empresa#create'
  get '/empresas/:nombre_empresa' => 'empresa#show', as: :empresa
  get '/empresas/:nombre_empresa/edit' => 'empresa#edit', as: :edit_empresa
  patch '/empresas/:nombre_empresa' => 'empresa#update'

  get 'signup'  => 'empresa#new'

  get '/proyectos' => 'proyecto#index'
  get '/proyectos/:id' => 'proyecto#show', as: :proyecto
  get '/empresas/:nombre_empresa/:id' => 'proyecto#show'
  get '/proyectos/:id/edit' => 'proyecto#edit', as: :edit_proyecto
  get '/empresas/:nombre_empresa/:id/edit' => 'proyecto#edit'
  patch '/proyectos/:id' => 'proyecto#update'
  get '/empresas/:nombre_empresa/proyectos/new' => 'proyecto#new'
  post '/proyectos' => 'proyecto#create'
  get '/empresas/:nombre_empresa/:id/delete' => 'proyecto#destroy'

  get '/disenios' => 'disenio#index'
  get '/disenios/:id' => 'disenio#show', as: :disenio
  get '/empresas/:nombre_empresa/:id_proyecto/:id_disenio' => 'disenio#show'
  get '/disenios/:id/edit' => 'disenio#edit', as: :edit_disenio
  get '/empresas/:nombre_empresa/:id_proyecto/:id_disenio/edit' => 'disenio#edit'
  patch '/disenios/:id' => 'disenio#update'
  get '/empresas/:nombre_empresa/:id_proyecto/disenios/new' => 'disenio#new'
  post '/disenios' => 'disenio#create'
  get '/empresas/:nombre_empresa/:id_proyecto/:id_disenio/destroy' => 'disenio#destroy'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

Grupo02-201610/app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
  belongs_to :empresa
  has_many :disenios
  self.per_page = 10
end

Grupo02-201610/app/controllers/proyecto_controller.rb
class ProyectoController < ApplicationController

  $proyecto_a

  def index
    @proyectos = Proyectody.all
  end

  def show
    @proyecto = Proyectody.find(params[:id])
    @empresa = Empresady.find_by_nombre_empresa(params[:nombre_empresa])
    ### NO ORDENA
    @disenios = @proyecto.disenios.where(estado: "Disponible")#.order(created_at: :desc)#.paginate(page: params[:page])
  end

  def new
    @proyecto = Proyecto.new
    @empresa = Empresady.find_by_nombre_empresa(params[:nombre_empresa])
  end

  def create
    @proyecto_nuevo = Proyecto.new(proyecto_params)
    if($proyecto_a == nil)
      @empresa = Empresady.find(current_empresa.id)
      @proyecto = @empresa.proyectos.create(proyecto_params)
      @proyecto.empresa = @empresa

      if(@proyecto.save)
        redirect_to "/empresas/#{@empresa.nombre_empresa}"
      else
        render 'new'
      end
    else
      self.update(@proyecto_nuevo)
    end
  end

  def edit
    @proyecto2 = Proyectody.find(params[:id])
    $proyecto_a = @proyecto2
    @proyecto = Proyecto.new(:nombre => @proyecto2.nombre ,:descripcion => @proyecto2.descripcion ,:valor_pagar => @proyecto2.valor_pagar)
  end

  def update(proyecto_nuevo)
    @proyecto_nuevo = proyecto_nuevo

    @proyecto = $proyecto_a

    @proyecto.nombre = @proyecto_nuevo.nombre
    @proyecto.descripcion = @proyecto_nuevo.descripcion
    @proyecto.valor_pagar = @proyecto_nuevo.valor_pagar

    @empresa = @proyecto.empresa
    if @proyecto.save
      $proyecto_a = nil
      redirect_to "/empresas/#{@empresa.nombre_empresa}"
    else
      render 'edit'
    end
  end

  def destroy
    @proyecto = Proyectody.find(params[:id])
    @empresa = Empresady.find_by_nombre_empresa(params[:nombre_empresa])
    @proyecto.disenios.each do |d|
      d.delete
    end
    @proyecto.delete
    #Proyectody.delete(@proyecto)
    redirect_to "/empresas/#{@empresa.nombre_empresa}"
  end

  private
    def proyecto_params
      params.require(:proyecto).permit(:nombre, :descripcion, :valor_pagar)
    end
  private
    def proyecto_params2
      params.require(:proyecto).permit(:nombre, :descripcion, :valor_pagar, :empresa_ids)
    end

end

Grupo02-201610/app/helpers/proyecto_helper.rb
module ProyectoHelper
end

Grupo02-201610/app/views/proyecto/edit.html.erb
<% provide(:info_empresa_active, "active") %>
<% provide(:title, "Editar Proyecto") %>

<div class="create">
  <div class="container">
    <div class="page-header">
      <h1>Editar proyecto <%= @proyecto.nombre%></h1>
    </div>
    <%= form_for(@proyecto, :html => {:class => 'form-horizontal'}) do |d| %>
    <div class="form-group">
      <label for="nombreProyecto" class="col-sm-2 control-label">Nombre</label>
      <div class="col-sm-10">
        <%= d.text_field :nombre, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="descripcionProyecto" class="col-sm-2 control-label">Descripcion</label>
      <div class="col-sm-10">
        <%= d.text_area :descripcion, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="cantidadProyecto" class="col-sm-2 control-label">Cantidad</label>
      <div class="col-sm-10">
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <p><%= d.number_field :valor_pagar, :class => "form-control" %></p>
          <div class="input-group-addon">.00</div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= d.submit value="Guardar cambios", :class => "btn btn-primary" %>
        <%= d.button value="Restaturar valores", type: :reset, :class => "btn btn-default" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

Grupo02-201610/app/views/proyecto/index.html.erb
<% provide(:info_empresa_active, "active") %>
<% provide(:title, "Proyectos") %>


<h1>Proyectos</h1>
<p>A continuación se muestra todos los proyectos que hay sin discriminar la empresa a la que pertenecen</p>
<div class="content">
  <% @proyectos.each do |p| %>
      <div class="context-row">
        <h3><b>Nombre: </b><%= p.nombre %></h3>
        <h3><b>Descripción: </b><%= p.descripcion %></h3>
        <h3><b>Valor a pagar: </b><%= p.valor_pagar %></h3>
        <h3><%= link_to "Ver más", proyecto_path(p) %></h3>
        <h3><%= link_to "Editar", edit_proyecto_path(p) %></h3>

      </div>
  <% end %>
</div>

Grupo02-201610/app/views/proyecto/new.html.erb
<% provide(:info_empresa_active, "active") %>
<% provide(:title, "Crear Proyecto") %>

<div class="create">
  <div class="container">
    <div class="page-header">
      <h1>Nuevo proyecto</h1>
    </div>
    <%= form_for(@proyecto, :html => {:class => 'form-horizontal'}) do |d| %>
    <div class="form-group">
      <label for="nombreProyecto" class="col-sm-2 control-label">Nombre</label>
      <div class="col-sm-10">
        <%= d.text_field :nombre, :placeholder => "Nombre", :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="descripcionProyecto" class="col-sm-2 control-label">Descripcion</label>
      <div class="col-sm-10">
        <%= d.text_area :descripcion, :placeholder => "Descripción", :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="cantidadProyecto" class="col-sm-2 control-label">Cantidad</label>
      <div class="col-sm-10">
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <p><%= d.number_field :valor_pagar, :class => "form-control" %></p>
          <div class="input-group-addon">.00</div>
        </div>
      </div>
    </div>

    <%= d.hidden_field :empresa_ids, :value=>@empresa.id, :readonly => true %></p>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= d.submit value="Guardar cambios", :class => "btn btn-primary" %>
        <%= d.button value="Restaturar valores", type: :reset, :class => "btn btn-default" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

Grupo02-201610/app/views/proyecto/show.html.erb
<% provide(:info_empresa_active, "active") %>
<% provide(:title, "#{@proyecto.nombre}") %>

<div class="container">
  <div class="page-header">
    <h1><small>Proyecto: </small> <%= @proyecto.nombre %></h1>
  </div>
  <% if current_empresa %>
  <div class="btn-group" role="group" aria-label="...">
    <%= link_to "Crear nuevo diseño", "/empresas/#{@empresa.nombre_empresa}/#{@proyecto.id}/disenios/new", :class => "btn btn-success" %>
    <%= link_to "Editar proyecto", "/empresas/#{@empresa.nombre_empresa}/#{@proyecto.id}/edit", :class => "btn btn-warning"  %>
    <%= link_to "Eliminar proyecto", "/empresas/#{@empresa.nombre_empresa}/#{@proyecto.id}/delete", :class => "btn btn-danger"  %>
  </div>
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th><h2>#</h2></th>
        <th><h2>Nombre</h2></th>
        <th><h2>Email</h2></th>
        <th><h2>Precio</h2></th>
        <th><h2>Fecha</h2></th>
        <th><h2>Estado</h2></th>
        <th><h2>Opciones</h2></th>
      </tr>
    </thead>
    <% num = 1 %>
    <% @disenios.each do |p| %>
        <tr>
          
          <th scope=row><p><%= num %></p></th>
          <td><p><%= p.nombre_diseniador %> <%= p.apellido_diseniador%></p></td>
          <td><p><%= p.email_diseniador %></p></td>
          <td><p>$<%= p.precio_solicitado %></p></td>
          <td><p><%= p.created_at %></p></td>
          <td><p><%= p.estado %></p></td>
          <td>
            <div class="btn-group btn-group-sm" role="group" aria-label="...">
              <%= link_to "Ver más", "/empresas/#{@empresa.nombre_empresa}/#{@proyecto.id}/#{p.id}", :class => "btn btn-info btn-sm", :role => "button"  %>
            </div>
          </td>
        </tr>
        <%num = num + 1%>
    <% end %>
  </table>

  <% else %>
  <div class="well">
    <%= link_to "Crear nuevo diseño", "/empresas/#{@empresa.nombre_empresa}/#{@proyecto.id}/disenios/new", :class => "btn btn-success" %>
  </div>

  <div class="row">
    <% num = 1 %>
    <% @disenios.each do |p| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag p.picture.url if p.picture? %>
        <div class="caption">
          <h3>Diseño <%= num %></h3>
          <p><h3>Fecha:</h3> <%= p.created_at %></p>
        </div>
      </div>
    </div>
    <% num += 1 %>
    <% end %>
  </div>

  <% end %>
</div>