Grupo02-201610/config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about' => 'pages#about', as: :about

  get '/empresas' => 'empresa#index'
  post 'empresas' => 'empresa#create'
  get '/empresas/:nombre_empresa' => 'empresa#show', as: :empresa
  get '/empresas/:nombre_empresa/edit' => 'empresa#edit', as: :edit_empresa
  patch '/empresas/:nombre_empresa' => 'empresa#update'

  get 'signup'  => 'empresa#new'

  get '/proyectos' => 'proyecto#index'
  get '/proyectos/:id' => 'proyecto#show', as: :proyecto
  get '/empresas/:nombre_empresa/:id' => 'proyecto#show'
  get '/proyectos/:id/edit' => 'proyecto#edit', as: :edit_proyecto
  get '/empresas/:nombre_empresa/:id/edit' => 'proyecto#edit'
  patch '/proyectos/:id' => 'proyecto#update'
  get '/empresas/:nombre_empresa/proyectos/new' => 'proyecto#new'
  post '/proyectos' => 'proyecto#create'
  get '/empresas/:nombre_empresa/:id/delete' => 'proyecto#destroy'

  get '/disenios' => 'disenio#index'
  get '/disenios/:id' => 'disenio#show', as: :disenio
  get '/empresas/:nombre_empresa/:id_proyecto/:id_disenio' => 'disenio#show'
  get '/disenios/:id/edit' => 'disenio#edit', as: :edit_disenio
  get '/empresas/:nombre_empresa/:id_proyecto/:id_disenio/edit' => 'disenio#edit'
  patch '/disenios/:id' => 'disenio#update'
  get '/empresas/:nombre_empresa/:id_proyecto/disenios/new' => 'disenio#new'
  post '/disenios' => 'disenio#create'
  get '/empresas/:nombre_empresa/:id_proyecto/:id_disenio/destroy' => 'disenio#destroy'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

Grupo02-201610/app/views/shared/_error_messages.html.erb
<% if @disenio.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Hay <%= pluralize(@disenio.errors.count, "error") %>.
      <ul>
      <% @disenio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

  </div>
<% end %>

Grupo02-201610/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">DesignMatch</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<!--  [OPCION] Login
      <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
      </form>
-->
      <ul class="nav navbar-nav navbar-right" >

        <% if current_empresa %>
          <li class="<%= yield(:home_active) %>"><%= link_to "Inicio", root_path %></li>
          <li class="<%= yield(:info_empresa_active) %>"><%= link_to "Proyectos", "/empresas/#{current_empresa.nombre_empresa}" %></li>
          <li class="<%= yield(:about_active) %>"><%= link_to "Nosotros", about_path %></li>
          <li class="dropdown <%= yield(:options_active)%>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Opciones <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil Empresa", "/empresas/#{current_empresa.id}/edit" %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Cerrar Sesión", logout_path, method: "delete" %></li>
            </ul>
          </li>
          <li>

          </li>
        <% else %>
          <li class="<%= yield(:home_active) %>"><%= link_to "Inicio", root_path %></li>
          <li class="<%= yield(:about_active) %>"><%= link_to "Nosotros", about_path %></li>
        <% end %>
      </ul>

<!--   [OPCION] Otros listados de Navegacion
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    -->

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>